# DATA AUDIT

In [3]:
import pandas as pd


DATA_PATH = "../data/raw/ronaldo_complete_ml_dataset.csv"

df = pd.read_csv(DATA_PATH)

print("Dataset shape:", df.shape)
print("\nFirst 5 rows:")
display(df.head())

print("\nLast 5 rows:")
display(df.tail())

print("\nTotal columns:", len(df.columns))
print("\nColumns:")
print(df.columns.tolist())

Dataset shape: (1333, 86)

First 5 rows:

,match_id,date,season,team,opponent,competition,competition_type,venue,is_national_team,competition_importance,...,venue_goals_per_game_pre,month,day_of_week,season_progress_pct,is_season_opening_phase,is_season_run_in,is_dec_jan_congestion,target_scored,target_multi_goal,target_goals
0,2002-08-14_Sporting_CP_Inter_Milan_1,2002-08-14,2002/03,Sporting CP,Inter Milan,Champions League Qualifying,continental_club,H,0,0.72,...,NaN,8,Wednesday,0.0357,1,0,0,0,0,0
1,2002-09-19_Portugal_Partizan_Belgrade_2,2002-09-19,2002/03,Portugal,Partizan Belgrade,UEFA Europa League,international,H,1,0.84,...,0.0,9,Thursday,0.1346,1,0,0,0,0,0
2,2002-09-30_Sporting_CP_Sporting_Braga_3,2002-09-30,2002/03,Sporting CP,Sporting Braga,Primeira Liga,domestic_league,A,0,0.78,...,NaN,9,Monday,0.1648,1,0,0,0,0,0
3,2002-10-03_Portugal_Partizan_Belgrade_4,2002-10-03,2002/03,Portugal,Partizan Belgrade,UEFA Europa League,international,A,1,0.84,...,0.0,10,Thursday,0.1731,1,0,0,0,0,0
4,2002-10-07_Sporting_CP_Moreirense_5,2002-10-07,2002/03,Sporting CP,Moreirense,Primeira Liga,domestic_league,H,0,0.78,...,0.0,10,Monday,0.1841,1,0,0,1,1,2

Last 5 rows:

,match_id,date,season,team,opponent,competition,competition_type,venue,is_national_team,competition_importance,...,venue_goals_per_game_pre,month,day_of_week,season_progress_pct,is_season_opening_phase,is_season_run_in,is_dec_jan_congestion,target_scored,target_multi_goal,target_goals
1328,2026-07-02_Portugal_Croatia_1329,2026-07-02,2025/26,Portugal,Croatia,World Cup,international,H,1,1.00,...,0.8053,7,Thursday,0.9203,0,1,0,1,0,1
1329,2026-07-06_Portugal_Spain_1330,2026-07-06,2025/26,Portugal,Spain,World Cup,international,H,1,1.00,...,0.8056,7,Monday,0.9313,0,1,0,0,0,0
1330,2026-08-21_Al-Nassr_Al_Riyadh_1331,2026-08-21,2026/27,Al-Nassr,Al Riyadh,Pro League,domestic_league,A,0,0.78,...,0.6694,8,Friday,0.0549,1,0,0,1,0,1
1331,2026-08-25_Al-Nassr_Al-Ettifaq_1332,2026-08-25,2026/27,Al-Nassr,Al-Ettifaq,Pro League,domestic_league,A,0,0.78,...,0.6699,8,Tuesday,0.0659,1,0,0,0,0,0
1332,2026-08-28_Al-Nassr_Al_Taawon_1333,2026-08-28,2026/27,Al-Nassr,Al Taawon,Pro League,domestic_league,H,0,0.78,...,0.8044,8,Friday,0.0742,1,0,0,1,0,1

Total columns: 86

Columns:
['match_id', 'date', 'season', 'team', 'opponent', 'competition', 'competition_type', 'venue', 'is_national_team', 'competition_importance', 'age_years', 'age_days', 'career_appearances_pre', 'career_goals_pre', 'career_assists_pre', 'goals_to_1000_pre', 'career_goals_per_game_pre', 'days_rest', 'matches_last_7d', 'matches_last_14d', 'matches_last_30d', 'goals_last_3', 'goals_last_5', 'goals_last_10', 'goals_last_20', 'assists_last_5', 'assists_last_10', 'goals_per_game_last_5', 'goals_per_game_last_10', 'goals_per_game_last_20', 'scoring_rate_last_5', 'scoring_rate_last_10', 'multi_goal_rate_last_10', 'goals_ewma_pre', 'assists_ewma_pre', 'consecutive_scoring_games_pre', 'goalless_streak_games_pre', 'days_since_last_goal', 'season_appearances_pre', 'season_goals_pre', 'season_assists_pre', 'season_goals_per_game_pre', 'team_appearances_with_ronaldo_pre', 'team_goals_by_ronaldo_pre', 'team_ronaldo_goals_per_game_pre', 'team_points_last_5_ronaldo_apps_pre', 'team_points_last_10_ronaldo_apps_pre', 'team_win_rate_last_5_ronaldo_apps_pre', 'team_unbeaten_rate_last_5_ronaldo_apps_pre', 'team_goals_for_last_5_scored_matches_pre', 'team_goals_against_last_5_scored_matches_pre', 'team_score_coverage_last_5_pre', 'opponent_prior_meetings_pre', 'ronaldo_goals_vs_opponent_pre', 'ronaldo_assists_vs_opponent_pre', 'ronaldo_goals_per_game_vs_opponent_pre', 'ronaldo_scoring_rate_vs_opponent_pre', 'ronaldo_goals_last_3_vs_opponent_pre', 'team_h2h_wins_pre', 'team_h2h_draws_pre', 'team_h2h_losses_pre', 'opponent_h2h_points_per_game_pre', 'opponent_h2h_unbeaten_rate_pre', 'opponent_goals_for_per_h2h_scored_match_pre', 'opponent_goals_against_per_h2h_scored_match_pre', 'opponent_clean_sheet_rate_h2h_scored_match_pre', 'opponent_score_data_h2h_matches_pre', 'team_matchup_elo_pre', 'opponent_matchup_elo_pre', 'matchup_elo_diff_pre', 'opponent_matchup_elo_games_pre', 'competition_appearances_pre', 'competition_goals_pre', 'competition_goals_per_game_pre', 'venue_appearances_pre', 'venue_goals_pre', 'venue_goals_per_game_pre', 'month', 'day_of_week', 'season_progress_pct', 'is_season_opening_phase', 'is_season_run_in', 'is_dec_jan_congestion', 'target_scored', 'target_multi_goal', 'target_goals']

## Core reconciliation and chronology checks

In [6]:


# Convert the date column from text/string into a proper
# pandas datetime type so chronological checks work correctly.
df["date"] = pd.to_datetime(df["date"])

# Sort the dataset by match date from oldest to newest.
# reset_index(drop=True) gives the dataframe a clean 0...N index.
df = df.sort_values("date").reset_index(drop=True)


# Number of matches/appearances in the dataset.
print("Total appearances:", len(df))

# Total career goals represented by the target column.
print("Total goals:", df["target_goals"].sum())

# Check how many unique match IDs exist.
print("Unique match IDs:", df["match_id"].nunique())

# Check whether any match_id occurs more than once.
print("Duplicate match IDs:", df["match_id"].duplicated().sum())



# Earliest match in the dataset.
print("First match date:", df["date"].min())

# Latest match in the dataset.
print("Last match date:", df["date"].max())

# True means every row is ordered chronologically.
print("Dates monotonically increasing:", df["date"].is_monotonic_increasing)



# HARD ASSERTIONS
# These should all pass silently.
# If one fails, Python will raise an AssertionError.

assert len(df) == 1333, "Unexpected number of appearances."

assert df["target_goals"].sum() == 978, \
    "Career goal total does not reconcile to 978."

assert df["match_id"].is_unique, \
    "Duplicate match IDs exist."

assert df["date"].is_monotonic_increasing, \
    "Dataset is not ordered chronologically."


print("\nAll Step 1B core checks passed.")

Total appearances: 1333
Total goals: 978
Unique match IDs: 1333
Duplicate match IDs: 0
First match date: 2002-08-14 00:00:00
Last match date: 2026-08-28 00:00:00
Dates monotonically increasing: True

All Step 1B core checks passed.

## Target integrity

In [9]:
print("Goal-count distribution:")
print(df["target_goals"].value_counts().sort_index())

print("\nTarget value ranges:")
print("target_goals:", sorted(df["target_goals"].unique()))
print("target_scored:", sorted(df["target_scored"].unique()))
print("target_multi_goal:", sorted(df["target_multi_goal"].unique()))

# Check that the derived binary targets agree with target_goals
scored_mismatch = df[
    df["target_scored"] != (df["target_goals"] > 0).astype(int)
]

multi_mismatch = df[
    df["target_multi_goal"] != (df["target_goals"] >= 2).astype(int)
]

print("\nNegative goal rows:", (df["target_goals"] < 0).sum())
print("target_scored mismatches:", len(scored_mismatch))
print("target_multi_goal mismatches:", len(multi_mismatch))

Goal-count distribution:
target_goals
0    676
1    415
2    176
3     55
4      9
5      2
Name: count, dtype: int64

Target value ranges:
target_goals: [0, 1, 2, 3, 4, 5]
target_scored: [0, 1]
target_multi_goal: [0, 1]

Negative goal rows: 0
target_scored mismatches: 0
target_multi_goal mismatches: 0

## Missing-value audit

In [12]:
# Missing-value audit

missing = (
    df.isna()
      .sum()
      .to_frame("missing_count")
)

missing["missing_pct"] = (missing["missing_count"] / len(df) * 100).round(2)

# Show only columns containing missing values
missing = missing[missing["missing_count"] > 0].sort_values(
    "missing_count",
    ascending=False
)

print("Columns with missing values:", len(missing))
print("Columns with no missing values:", df.shape[1] - len(missing))

display(missing)

Columns with missing values: 26
Columns with no missing values: 60

                                                 missing_count  missing_pct
opponent_clean_sheet_rate_h2h_scored_match_pre             679        50.94
opponent_goals_against_per_h2h_scored_match_pre            679        50.94
opponent_goals_for_per_h2h_scored_match_pre                679        50.94
team_goals_for_last_5_scored_matches_pre                   432        32.41
team_goals_against_last_5_scored_matches_pre               432        32.41
opponent_h2h_unbeaten_rate_pre                             298        22.36
opponent_h2h_points_per_game_pre                           298        22.36
ronaldo_scoring_rate_vs_opponent_pre                       298        22.36
ronaldo_goals_per_game_vs_opponent_pre                     298        22.36
competition_goals_per_game_pre                              31         2.33
season_goals_per_game_pre                                   25         1.88
team_win_rate_last_5_ronaldo_apps_pre                        6         0.45
team_ronaldo_goals_per_game_pre                              6         0.45
team_unbeaten_rate_last_5_ronaldo_apps_pre                   6         0.45
days_since_last_goal                                         5         0.38
venue_goals_per_game_pre                                     3         0.23
days_rest                                                    1         0.08
assists_ewma_pre                                             1         0.08
goals_ewma_pre                                               1         0.08
multi_goal_rate_last_10                                      1         0.08
scoring_rate_last_10                                         1         0.08
scoring_rate_last_5                                          1         0.08
goals_per_game_last_20                                       1         0.08
goals_per_game_last_10                                       1         0.08
goals_per_game_last_5                                        1         0.08
career_goals_per_game_pre                                    1         0.08

In [14]:
# Check whether H2H missingness is structurally expected

h2h_check = df[
    [
        "date",
        "opponent",
        "opponent_prior_meetings_pre",
        "opponent_score_data_h2h_matches_pre",
        "ronaldo_goals_per_game_vs_opponent_pre",
        "opponent_goals_for_per_h2h_scored_match_pre",
        "opponent_goals_against_per_h2h_scored_match_pre",
        "opponent_clean_sheet_rate_h2h_scored_match_pre",
    ]
].copy()

# Compare missingness with the amount of prior H2H information available
print("Rows with NO prior opponent meetings:")
print((h2h_check["opponent_prior_meetings_pre"] == 0).sum())

print("\nRows with NO prior verified-score H2H matches:")
print((h2h_check["opponent_score_data_h2h_matches_pre"] == 0).sum())

print("\nMissing Ronaldo H2H GPG:")
print(h2h_check["ronaldo_goals_per_game_vs_opponent_pre"].isna().sum())

print("\nMissing score-based opponent H2H stats:")
print(
    h2h_check[
        "opponent_goals_for_per_h2h_scored_match_pre"
    ].isna().sum()
)

# Look for suspicious cases: prior history exists, but the feature is still missing
suspicious_h2h = h2h_check[
    (h2h_check["opponent_score_data_h2h_matches_pre"] > 0)
    & (
        h2h_check[
            "opponent_goals_for_per_h2h_scored_match_pre"
        ].isna()
    )
]

print("\nPrior verified H2H exists but score-based feature is missing:")
print(len(suspicious_h2h))

Rows with NO prior opponent meetings:
298

Rows with NO prior verified-score H2H matches:
679

Missing Ronaldo H2H GPG:
298

Missing score-based opponent H2H stats:
679

Prior verified H2H exists but score-based feature is missing:
0

## Basic football-domain sanity checks

In [17]:
print("Invalid venues:")
print(df.loc[~df["venue"].isin(["H", "A", "N"]), "venue"].value_counts())

print("\nAge range:")
print("Minimum:", df["age_years"].min())
print("Maximum:", df["age_years"].max())

print("\nInvalid national-team flags:")
print(df.loc[~df["is_national_team"].isin([0, 1]), "is_national_team"].value_counts())

print("\nCompetition importance range:")
print(
    df["competition_importance"].min(),
    "to",
    df["competition_importance"].max()
)

print("\nAppearances by team:")
print(df.groupby("team").size().sort_values(ascending=False))

Invalid venues:
Series([], Name: count, dtype: int64)

Age range:
Minimum: 17.5199
Maximum: 41.5587

Invalid national-team flags:
Series([], Name: count, dtype: int64)

Competition importance range:
0.35 to 1.0

Appearances by team:
team
Real Madrid          432
Manchester United    338
Portugal             249
Al-Nassr             151
Juventus             134
Sporting CP           29
dtype: int64

## Team ↔ national-team consistency

In [20]:
team_flag_check = pd.crosstab(
    df["team"],
    df["is_national_team"]
)

display(team_flag_check)

# Find any rows where the team and national-team flag disagree
invalid_team_flags = df[
    ((df["team"] == "Portugal") & (df["is_national_team"] != 1))
    |
    ((df["team"] != "Portugal") & (df["is_national_team"] != 0))
]

print("\nInconsistent team/national-team rows:", len(invalid_team_flags))

is_national_team     0    1
team
Al-Nassr           151    0
Juventus           134    0
Manchester United  338    0
Portugal             0  249
Real Madrid        432    0
Sporting CP         29    0

Inconsistent team/national-team rows: 0

## Audit competition labels and types

In [23]:
competition_summary = (
    df.groupby(["competition", "competition_type"])
      .size()
      .reset_index(name="appearances")
      .sort_values(["competition_type", "competition", "appearances"])
)

print("Unique competitions:", df["competition"].nunique())
print("Unique competition types:", df["competition_type"].nunique())

print("\nCompetition types:")
print(df["competition_type"].value_counts())

print("\nCompetition mapping:")
display(competition_summary)

Unique competitions: 31
Unique competition types: 4

Competition types:
competition_type
domestic_league          761
international            249
continental_club         208
domestic_or_other_cup    115
Name: count, dtype: int64

Competition mapping:

                         competition       competition_type  appearances
0               AFC Champions League       continental_club            9
1         AFC Champions League Elite       continental_club            8
2           AFC Champions League Two       continental_club            4
4        Champions League Qualifying       continental_club            4
25             UEFA Champions League       continental_club          183
15                           La Liga        domestic_league          292
17                    Premier League        domestic_league          236
18                     Primeira Liga        domestic_league           25
19                        Pro League        domestic_league          110
21                           Serie A        domestic_league           98
3            Arab Club Champions Cup  domestic_or_other_cup            6
6                       Copa del Rey  domestic_or_other_cup           30
7                       Coppa Italia  domestic_or_other_cup           10
10               FA Community Shield  domestic_or_other_cup            1
11                            FA Cup  domestic_or_other_cup           27
14                        King's Cup  domestic_or_other_cup            8
16                        League Cup  domestic_or_other_cup           12
20                   Saudi Super Cup  domestic_or_other_cup            6
22               Supercopa de Espana  domestic_or_other_cup            7
23               Supercoppa Italiana  domestic_or_other_cup            3
24                  Taça de Portugal  domestic_or_other_cup            3
28                    UEFA Super Cup  domestic_or_other_cup            2
5                 Confederations Cup          international            4
8                  Euro Championship          international           30
9                    Euros Qualifier          international           44
12               FIFA Club World Cup          international            8
13            International Friendly          international           56
26                UEFA Europa League          international            8
27               UEFA Nations League          international           20
29                         World Cup          international           27
30  World Cup - Qualification Europe          international           52

In [25]:
# Check which competitions are attached to each team

team_competitions = (
    df.groupby(["team", "competition"])
      .size()
      .reset_index(name="appearances")
      .sort_values(["team", "competition"])
)

display(team_competitions)

                 team                       competition  appearances
0            Al-Nassr              AFC Champions League            9
1            Al-Nassr        AFC Champions League Elite            8
2            Al-Nassr          AFC Champions League Two            4
3            Al-Nassr           Arab Club Champions Cup            6
4            Al-Nassr                        King's Cup            8
5            Al-Nassr                        Pro League          110
6            Al-Nassr                   Saudi Super Cup            6
7            Juventus                      Coppa Italia           10
8            Juventus                           Serie A           98
9            Juventus               Supercoppa Italiana            3
10           Juventus             UEFA Champions League           23
11  Manchester United       Champions League Qualifying            3
12  Manchester United               FA Community Shield            1
13  Manchester United                            FA Cup           27
14  Manchester United                        League Cup           12
15  Manchester United                    Premier League          236
16  Manchester United             UEFA Champions League           59
17           Portugal                Confederations Cup            4
18           Portugal                 Euro Championship           30
19           Portugal                   Euros Qualifier           44
20           Portugal               FIFA Club World Cup            8
21           Portugal            International Friendly           56
22           Portugal                UEFA Europa League            8
23           Portugal               UEFA Nations League           20
24           Portugal                         World Cup           27
25           Portugal  World Cup - Qualification Europe           52
26        Real Madrid                      Copa del Rey           30
27        Real Madrid                           La Liga          292
28        Real Madrid               Supercopa de Espana            7
29        Real Madrid             UEFA Champions League          101
30        Real Madrid                    UEFA Super Cup            2
31        Sporting CP       Champions League Qualifying            1
32        Sporting CP                     Primeira Liga           25
33        Sporting CP                  Taça de Portugal            3

In [27]:
# Inspect Portugal rows assigned to club competitions

suspicious_portugal = df[
    (df["team"] == "Portugal")
    & (df["competition"].isin([
        "FIFA Club World Cup",
        "UEFA Europa League"
    ]))
][
    [
        "match_id",
        "date",
        "season",
        "team",
        "opponent",
        "competition",
        "competition_type",
        "venue",
        "target_goals"
    ]
].sort_values("date")

display(suspicious_portugal)

,match_id,date,season,team,opponent,competition,competition_type,venue,target_goals
1,2002-09-19_Portugal_Partizan_Belgrade_2,2002-09-19,2002/03,Portugal,Partizan Belgrade,UEFA Europa League,international,H,0
3,2002-10-03_Portugal_Partizan_Belgrade_4,2002-10-03,2002/03,Portugal,Partizan Belgrade,UEFA Europa League,international,A,0
350,2008-12-18_Portugal_Gamba_Osaka_351,2008-12-18,2008/09,Portugal,Gamba Osaka,FIFA Club World Cup,international,N,1
351,2008-12-21_Portugal_Liga_de_Quito_352,2008-12-21,2008/09,Portugal,Liga de Quito,FIFA Club World Cup,international,N,0
710,2014-12-16_Portugal_Cruz_Azul_711,2014-12-16,2014/15,Portugal,Cruz Azul,FIFA Club World Cup,international,A,0
711,2014-12-20_Portugal_San_Lorenzo_712,2014-12-20,2014/15,Portugal,San Lorenzo,FIFA Club World Cup,international,H,0
824,2016-12-15_Portugal_Club_America_825,2016-12-15,2016/17,Portugal,Club America,FIFA Club World Cup,international,A,1
825,2016-12-18_Portugal_Kashima_826,2016-12-18,2016/17,Portugal,Kashima,FIFA Club World Cup,international,H,3
883,2017-12-13_Portugal_Al-Jazira_884,2017-12-13,2017/18,Portugal,Al-Jazira,FIFA Club World Cup,international,A,1
884,2017-12-16_Portugal_Gremio_885,2017-12-16,2017/18,Portugal,Gremio,FIFA Club World Cup,international,H,1
1128,2022-09-08_Portugal_Real_Sociedad_1129,2022-09-08,2022/23,Portugal,Real Sociedad,UEFA Europa League,international,H,0
1129,2022-09-15_Portugal_Sheriff_Tiraspol_1130,2022-09-15,2022/23,Portugal,Sheriff Tiraspol,UEFA Europa League,international,A,1
1132,2022-10-06_Portugal_Omonia_Nicosia_1133,2022-10-06,2022/23,Portugal,Omonia Nicosia,UEFA Europa League,international,A,0
1134,2022-10-13_Portugal_Omonia_Nicosia_1135,2022-10-13,2022/23,Portugal,Omonia Nicosia,UEFA Europa League,international,H,0
1136,2022-10-27_Portugal_Sheriff_Tiraspol_1137,2022-10-27,2022/23,Portugal,Sheriff Tiraspol,UEFA Europa League,international,H,1
1138,2022-11-03_Portugal_Real_Sociedad_1139,2022-11-03,2022/23,Portugal,Real Sociedad,UEFA Europa League,international,A,0

In [29]:
# Inspect matches surrounding the suspicious rows

suspicious_idx = df.index[
    (df["team"] == "Portugal")
    & (df["competition"].isin([
        "FIFA Club World Cup",
        "UEFA Europa League"
    ]))
]

context_idx = set()

for idx in suspicious_idx:
    for nearby_idx in range(max(0, idx - 1), min(len(df), idx + 2)):
        context_idx.add(nearby_idx)

context = df.loc[sorted(context_idx), [
    "date",
    "team",
    "opponent",
    "competition",
    "target_goals"
]]

display(context)

,date,team,opponent,competition,target_goals
0,2002-08-14,Sporting CP,Inter Milan,Champions League Qualifying,0
1,2002-09-19,Portugal,Partizan Belgrade,UEFA Europa League,0
2,2002-09-30,Sporting CP,Sporting Braga,Primeira Liga,0
3,2002-10-03,Portugal,Partizan Belgrade,UEFA Europa League,0
4,2002-10-07,Sporting CP,Moreirense,Primeira Liga,2
349,2008-12-13,Manchester United,Tottenham Hotspur,Premier League,0
350,2008-12-18,Portugal,Gamba Osaka,FIFA Club World Cup,1
351,2008-12-21,Portugal,Liga de Quito,FIFA Club World Cup,0
352,2008-12-26,Manchester United,Stoke City,Premier League,0
709,2014-12-12,Real Madrid,Almeria,La Liga,2
710,2014-12-16,Portugal,Cruz Azul,FIFA Club World Cup,0
711,2014-12-20,Portugal,San Lorenzo,FIFA Club World Cup,0
712,2015-01-04,Real Madrid,Valencia,La Liga,1
823,2016-12-07,Real Madrid,Borussia Dortmund,UEFA Champions League,0
824,2016-12-15,Portugal,Club America,FIFA Club World Cup,1
825,2016-12-18,Portugal,Kashima,FIFA Club World Cup,3
826,2017-01-07,Real Madrid,Granada CF,La Liga,1
882,2017-12-09,Real Madrid,Sevilla,La Liga,2
883,2017-12-13,Portugal,Al-Jazira,FIFA Club World Cup,1
884,2017-12-16,Portugal,Gremio,FIFA Club World Cup,1
885,2017-12-23,Real Madrid,Barcelona,La Liga,0
1127,2022-09-04,Manchester United,Arsenal,Premier League,0
1128,2022-09-08,Portugal,Real Sociedad,UEFA Europa League,0
1129,2022-09-15,Portugal,Sheriff Tiraspol,UEFA Europa League,1
1130,2022-09-24,Portugal,Czech Republic,UEFA Nations League,0
1131,2022-09-27,Portugal,Spain,UEFA Nations League,0
1132,2022-10-06,Portugal,Omonia Nicosia,UEFA Europa League,0
1133,2022-10-09,Manchester United,Everton,Premier League,1
1134,2022-10-13,Portugal,Omonia Nicosia,UEFA Europa League,0
1135,2022-10-16,Manchester United,Newcastle,Premier League,0
1136,2022-10-27,Portugal,Sheriff Tiraspol,UEFA Europa League,1
1137,2022-10-30,Manchester United,West Ham,Premier League,0
1138,2022-11-03,Portugal,Real Sociedad,UEFA Europa League,0
1139,2022-11-06,Manchester United,Aston Villa,Premier League,0

In [33]:
# Review every opponent recorded under Portugal

portugal_opponents = (
    df[df["team"] == "Portugal"]
    .groupby(["opponent", "competition"])
    .size()
    .reset_index(name="appearances")
    .sort_values(["competition", "opponent"])
)

# Show the complete Portugal opponent audit

with pd.option_context("display.max_rows", None):
    display(portugal_opponents)

                   opponent                       competition  appearances
24                    Chile                Confederations Cup            1
88                   Mexico                Confederations Cup            1
95              New Zealand                Confederations Cup            1
114                  Russia                Confederations Cup            1
10                  Austria                 Euro Championship            1
13                  Belgium                 Euro Championship            1
30                  Croatia                 Euro Championship            1
36           Czech Republic                 Euro Championship            3
38                  Denmark                 Euro Championship            1
45                  England                 Euro Championship            1
54                   France                 Euro Championship            3
59                  Georgia                 Euro Championship            1
61                  Germany                 Euro Championship            3
65                   Greece                 Euro Championship            2
67                  Hungary                 Euro Championship            2
69                  Iceland                 Euro Championship            1
91              Netherlands                 Euro Championship            2
105                  Poland                 Euro Championship            1
115                  Russia                 Euro Championship            1
125                Slovenia                 Euro Championship            1
129                   Spain                 Euro Championship            2
140                 Türkiye                 Euro Championship            2
146                   Wales                 Euro Championship            1
1                   Albania                   Euros Qualifier            1
8                   Armenia                   Euros Qualifier            4
11               Azerbaijan                   Euros Qualifier            2
14                  Belgium                   Euros Qualifier            1
16     Bosnia & Herzegovina                   Euros Qualifier            2
17   Bosnia and Herzegovina                   Euros Qualifier            2
35                   Cyprus                   Euros Qualifier            1
39                  Denmark                   Euros Qualifier            4
52                  Finland                   Euros Qualifier            2
70                  Iceland                   Euros Qualifier            4
77               Kazakhstan                   Euros Qualifier            2
80            Liechtenstein                   Euros Qualifier            2
83                Lithuania                   Euros Qualifier            2
85               Luxembourg                   Euros Qualifier            3
101                  Norway                   Euros Qualifier            1
106                  Poland                   Euros Qualifier            2
120                  Serbia                   Euros Qualifier            5
123                Slovakia                   Euros Qualifier            2
143                 Ukraine                   Euros Qualifier            2
0                 Al-Jazira               FIFA Club World Cup            1
27             Club America               FIFA Club World Cup            1
34                Cruz Azul               FIFA Club World Cup            1
58              Gamba Osaka               FIFA Club World Cup            1
66                   Gremio               FIFA Club World Cup            1
76                  Kashima               FIFA Club World Cup            1
82            Liga de Quito               FIFA Club World Cup            1
117             San Lorenzo               FIFA Club World Cup            1
2                   Albania            International Friendly            1
4                   Algeria            International Friendly            1
5                   Andorra            International Friendly            1
7                 Argentina            International Friendly            2
15                  Belgium            International Friendly            1
18                   Brazil            International Friendly            2
20                 Bulgaria            International Friendly            1
21                 Cameroon            International Friendly            2
22                   Canada            International Friendly            1
23               Cape Verde            International Friendly            2
25                    Chile            International Friendly            1
26                    China            International Friendly            1
31                  Croatia            International Friendly            2
40                  Denmark            International Friendly            1
43                  Ecuador            International Friendly            1
44                    Egypt            International Friendly            1
46                  England            International Friendly            1
48                  Estonia            International Friendly            1
53                  Finland            International Friendly            1
55                   France            International Friendly            2
60                  Georgia            International Friendly            1
72                   Israel            International Friendly            1
74                    Italy            International Friendly            2
78               Kazakhstan            International Friendly            1
84                Lithuania            International Friendly            1
86               Luxembourg            International Friendly            3
90               Mozambique            International Friendly            1
92              Netherlands            International Friendly            2
96                  Nigeria            International Friendly            1
98          North Macedonia            International Friendly            1
99         Northern Ireland            International Friendly            1
103                  Panama            International Friendly            1
107                  Poland            International Friendly            1
109                   Qatar            International Friendly            1
111         Rep. Of Ireland            International Friendly            1
113     Republic of Ireland            International Friendly            2
118            Saudi Arabia            International Friendly            1
126                Slovenia            International Friendly            1
127            South Africa            International Friendly            1
130                   Spain            International Friendly            3
133                  Sweden            International Friendly            2
139                  Turkey            International Friendly            1
102          Omonia Nicosia                UEFA Europa League            2
104       Partizan Belgrade                UEFA Europa League            2
110           Real Sociedad                UEFA Europa League            2
122        Sheriff Tiraspol                UEFA Europa League            2
32                  Croatia               UEFA Nations League            2
37           Czech Republic               UEFA Nations League            2
41                  Denmark               UEFA Nations League            2
56                   France               UEFA Nations League            2
62                  Germany               UEFA Nations League            1
93              Netherlands               UEFA Nations League            1
108                  Poland               UEFA Nations League            2
119                Scotland               UEFA Nations League            2
131                   Spain               UEFA Nations League            3
134                  Sweden               UEFA Nations League            1
136             Switzerland               UEFA Nations League            2
6                    Angola                         World Cup            1
19                   Brazil                         World Cup            1
28                 Colombia                         World Cup            1
29                 Congo DR                         World Cup            1
33                  Croatia                         World Cup            1
47                  England                         World Cup            1
57                   France                         World Cup            1
63                  Germany                         World Cup            2
64                    Ghana                         World Cup            2
71                     Iran                         World Cup            2
75              Ivory Coast                         World Cup            1
89                  Morocco                         World Cup            2
94              Netherlands                         World Cup            1
97              North Korea                         World Cup            1
128             South Korea                         World Cup            1
132                   Spain                         World Cup            3
137             Switzerland                         World Cup            1
142                     USA                         World Cup            1
144                 Uruguay                         World Cup            2
145              Uzbekistan                         World Cup            1
3                   Albania  World Cup - Qualification Europe            2
9                   Armenia  World Cup - Qualification Europe            1
12               Azerbaijan  World Cup - Qualification Europe            2
42                  Denmark  World Cup - Qualification Europe            1
49                  Estonia  World Cup - Qualification Europe            2
50            FYR Macedonia  World Cup - Qualification Europe            1
51            Faroe Islands  World Cup - Qualification Europe            2
68                  Hungary  World Cup - Qualification Europe            6
73                   Israel  World Cup - Qualification Europe            2
79                   Latvia  World Cup - Qualification Europe            4
81            Liechtenstein  World Cup - Qualification Europe            2
87               Luxembourg  World Cup - Qualification Europe            5
100        Northern Ireland  World Cup - Qualification Europe            2
112         Rep. Of Ireland  World Cup - Qualification Europe            4
116                  Russia  World Cup - Qualification Europe            4
121                  Serbia  World Cup - Qualification Europe            2
124                Slovakia  World Cup - Qualification Europe            2
135                  Sweden  World Cup - Qualification Europe            4
138             Switzerland  World Cup - Qualification Europe            1
141                 Türkiye  World Cup - Qualification Europe            1
147                 andorra  World Cup - Qualification Europe            2

In [35]:
# Inspect the suspicious Partizan Belgrade matches

partizan_rows = df[
    (df["opponent"] == "Partizan Belgrade")
][
    [
        "match_id",
        "date",
        "season",
        "team",
        "opponent",
        "competition",
        "competition_type",
        "venue",
        "age_years",
        "career_appearances_pre",
        "career_goals_pre",
        "season_appearances_pre",
        "team_appearances_with_ronaldo_pre",
        "competition_appearances_pre",
        "target_goals",
    ]
]

display(partizan_rows)

,match_id,date,season,team,opponent,competition,competition_type,venue,age_years,career_appearances_pre,career_goals_pre,season_appearances_pre,team_appearances_with_ronaldo_pre,competition_appearances_pre,target_goals
1,2002-09-19_Portugal_Partizan_Belgrade_2,2002-09-19,2002/03,Portugal,Partizan Belgrade,UEFA Europa League,international,H,17.6184,1,0,1,0,0,0
3,2002-10-03_Portugal_Partizan_Belgrade_4,2002-10-03,2002/03,Portugal,Partizan Belgrade,UEFA Europa League,international,A,17.6568,3,0,3,1,1,0

In [37]:
# Inspect Ronaldo's early career sequence

early_career = df[
    df["date"].between("2002-08-01", "2002-11-30")
][
    [
        "date",
        "team",
        "opponent",
        "competition",
        "venue",
        "target_goals"
    ]
].sort_values("date")

display(early_career)

,date,team,opponent,competition,venue,target_goals
0,2002-08-14,Sporting CP,Inter Milan,Champions League Qualifying,H,0
1,2002-09-19,Portugal,Partizan Belgrade,UEFA Europa League,H,0
2,2002-09-30,Sporting CP,Sporting Braga,Primeira Liga,A,0
3,2002-10-03,Portugal,Partizan Belgrade,UEFA Europa League,A,0
4,2002-10-07,Sporting CP,Moreirense,Primeira Liga,H,2
5,2002-10-20,Sporting CP,Belenenses,Primeira Liga,H,0
6,2002-10-26,Sporting CP,Boavista,Primeira Liga,A,1
7,2002-11-02,Sporting CP,Gil Vicente,Primeira Liga,H,0
8,2002-11-08,Sporting CP,Vitoria Guimaraes,Primeira Liga,A,0
9,2002-11-15,Sporting CP,Maritimo de Funchal,Primeira Liga,H,0
10,2002-11-24,Sporting CP,Estarreja,Taça de Portugal,H,1
11,2002-11-30,Sporting CP,Beira-Mar,Primeira Liga,A,0

In [39]:
# Check whether team-history features were built from the wrong team

team_corrections = {
    1: "Sporting CP",
    3: "Sporting CP",
    350: "Manchester United",
    351: "Manchester United",
    710: "Real Madrid",
    711: "Real Madrid",
    824: "Real Madrid",
    825: "Real Madrid",
    883: "Real Madrid",
    884: "Real Madrid",
    1128: "Manchester United",
    1129: "Manchester United",
    1132: "Manchester United",
    1134: "Manchester United",
    1136: "Manchester United",
    1138: "Manchester United",
}

impact_rows = []

for idx, correct_team in team_corrections.items():
    match_date = df.loc[idx, "date"]

    # Count earlier appearances for the club this match actually belongs to
    expected_team_apps = (
        (df["date"] < match_date)
        & (df["team"] == correct_team)
    ).sum()

    impact_rows.append({
        "date": match_date,
        "opponent": df.loc[idx, "opponent"],
        "stored_team": df.loc[idx, "team"],
        "correct_team": correct_team,
        "stored_team_apps_pre": df.loc[
            idx, "team_appearances_with_ronaldo_pre"
        ],
        "expected_team_apps_pre": expected_team_apps,
    })

team_impact = pd.DataFrame(impact_rows)

display(team_impact)

,date,opponent,stored_team,correct_team,stored_team_apps_pre,expected_team_apps_pre
0,2002-09-19,Partizan Belgrade,Portugal,Sporting CP,0,1
1,2002-10-03,Partizan Belgrade,Portugal,Sporting CP,1,2
2,2008-12-18,Gamba Osaka,Portugal,Manchester United,63,258
3,2008-12-21,Liga de Quito,Portugal,Manchester United,64,258
4,2014-12-16,Cruz Azul,Portugal,Real Madrid,122,269
5,2014-12-20,San Lorenzo,Portugal,Real Madrid,123,269
6,2016-12-15,Club America,Portugal,Real Madrid,142,363
7,2016-12-18,Kashima,Portugal,Real Madrid,143,363
8,2017-12-13,Al-Jazira,Portugal,Real Madrid,155,409
9,2017-12-16,Gremio,Portugal,Real Madrid,156,409
10,2022-09-08,Real Sociedad,Portugal,Manchester United,199,334
11,2022-09-15,Sheriff Tiraspol,Portugal,Manchester United,200,334
12,2022-10-06,Omonia Nicosia,Portugal,Manchester United,203,334
13,2022-10-13,Omonia Nicosia,Portugal,Manchester United,204,335
14,2022-10-27,Sheriff Tiraspol,Portugal,Manchester United,205,336
15,2022-11-03,Real Sociedad,Portugal,Manchester United,206,337

In [41]:
# Inspect team-history counters around each corrupted block

check_dates = [
    "2002-10-07",  # Sporting after Partizan
    "2008-12-26",  # Man United after Club World Cup
    "2015-01-04",  # Real Madrid after 2014 CWC
    "2017-01-07",  # Real Madrid after 2016 CWC
    "2017-12-23",  # Real Madrid after 2017 CWC
    "2022-11-06",  # Man United after Europa League block
]

downstream_check = df[
    df["date"].dt.strftime("%Y-%m-%d").isin(check_dates)
][
    [
        "date",
        "team",
        "opponent",
        "team_appearances_with_ronaldo_pre",
        "team_goals_by_ronaldo_pre",
        "team_ronaldo_goals_per_game_pre",
    ]
].sort_values("date")

display(downstream_check)

,date,team,opponent,team_appearances_with_ronaldo_pre,team_goals_by_ronaldo_pre,team_ronaldo_goals_per_game_pre
4,2002-10-07,Sporting CP,Moreirense,2,0,0.0000
352,2008-12-26,Manchester United,Stoke City,258,101,0.3915
712,2015-01-04,Real Madrid,Valencia,269,284,1.0558
826,2017-01-07,Real Madrid,Granada CF,363,376,1.0358
885,2017-12-23,Real Madrid,Barcelona,409,416,1.0171
1139,2022-11-06,Manchester United,Aston Villa,337,142,0.4214

In [43]:
# Find features that may depend on team identity

team_related_cols = [
    col for col in df.columns
    if any(keyword in col.lower() for keyword in [
        "team_",
        "matchup",
        "h2h"
    ])
]

print("Potential team-dependent columns:", len(team_related_cols))

for col in team_related_cols:
    print(col)

Potential team-dependent columns: 23
team_appearances_with_ronaldo_pre
team_goals_by_ronaldo_pre
team_ronaldo_goals_per_game_pre
team_points_last_5_ronaldo_apps_pre
team_points_last_10_ronaldo_apps_pre
team_win_rate_last_5_ronaldo_apps_pre
team_unbeaten_rate_last_5_ronaldo_apps_pre
team_goals_for_last_5_scored_matches_pre
team_goals_against_last_5_scored_matches_pre
team_score_coverage_last_5_pre
team_h2h_wins_pre
team_h2h_draws_pre
team_h2h_losses_pre
opponent_h2h_points_per_game_pre
opponent_h2h_unbeaten_rate_pre
opponent_goals_for_per_h2h_scored_match_pre
opponent_goals_against_per_h2h_scored_match_pre
opponent_clean_sheet_rate_h2h_scored_match_pre
opponent_score_data_h2h_matches_pre
team_matchup_elo_pre
opponent_matchup_elo_pre
matchup_elo_diff_pre
opponent_matchup_elo_games_pre

In [45]:
# Check whether career-level counters remain continuous

career_check = df.loc[
    [0, 1, 2, 3, 4, 349, 350, 351, 352],
    [
        "date",
        "team",
        "opponent",
        "career_appearances_pre",
        "career_goals_pre",
        "target_goals",
    ]
].copy()

career_check["expected_next_apps"] = (
    career_check["career_appearances_pre"] + 1
)

display(career_check)

,date,team,opponent,career_appearances_pre,career_goals_pre,target_goals,expected_next_apps
0,2002-08-14,Sporting CP,Inter Milan,0,0,0,1
1,2002-09-19,Portugal,Partizan Belgrade,1,0,0,2
2,2002-09-30,Sporting CP,Sporting Braga,2,0,0,3
3,2002-10-03,Portugal,Partizan Belgrade,3,0,0,4
4,2002-10-07,Sporting CP,Moreirense,4,0,2,5
349,2008-12-13,Manchester United,Tottenham Hotspur,349,127,0,350
350,2008-12-18,Portugal,Gamba Osaka,350,127,1,351
351,2008-12-21,Portugal,Liga de Quito,351,128,0,352
352,2008-12-26,Manchester United,Stoke City,352,128,0,353

In [47]:
# Check whether season-level counters remain continuous

season_check = df.loc[
    [349, 350, 351, 352, 1127, 1128, 1129, 1130, 1131, 1132, 1133],
    [
        "date",
        "team",
        "opponent",
        "season",
        "season_appearances_pre",
        "season_goals_pre",
        "target_goals",
    ]
].copy()

display(season_check)

,date,team,opponent,season,season_appearances_pre,season_goals_pre,target_goals
349,2008-12-13,Manchester United,Tottenham Hotspur,2008/09,21,9,0
350,2008-12-18,Portugal,Gamba Osaka,2008/09,22,9,1
351,2008-12-21,Portugal,Liga de Quito,2008/09,23,10,0
352,2008-12-26,Manchester United,Stoke City,2008/09,24,10,0
1127,2022-09-04,Manchester United,Arsenal,2022/23,5,0,0
1128,2022-09-08,Portugal,Real Sociedad,2022/23,6,0,0
1129,2022-09-15,Portugal,Sheriff Tiraspol,2022/23,7,0,1
1130,2022-09-24,Portugal,Czech Republic,2022/23,8,1,0
1131,2022-09-27,Portugal,Spain,2022/23,9,1,0
1132,2022-10-06,Portugal,Omonia Nicosia,2022/23,10,1,0
1133,2022-10-09,Manchester United,Everton,2022/23,11,1,1

In [49]:
# Check whether competition-level counters remain continuous

competition_check = df.loc[
    [350, 351, 710, 711, 824, 825, 883, 884, 1128, 1129, 1132, 1134, 1136, 1138],
    [
        "date",
        "team",
        "opponent",
        "competition",
        "competition_appearances_pre",
        "competition_goals_pre",
        "competition_goals_per_game_pre",
        "target_goals",
    ]
].copy()

display(competition_check)

,date,team,opponent,competition,competition_appearances_pre,competition_goals_pre,competition_goals_per_game_pre,target_goals
350,2008-12-18,Portugal,Gamba Osaka,FIFA Club World Cup,0,0,NaN,1
351,2008-12-21,Portugal,Liga de Quito,FIFA Club World Cup,1,1,1.0000,0
710,2014-12-16,Portugal,Cruz Azul,FIFA Club World Cup,2,1,0.5000,0
711,2014-12-20,Portugal,San Lorenzo,FIFA Club World Cup,3,1,0.3333,0
824,2016-12-15,Portugal,Club America,FIFA Club World Cup,4,1,0.2500,1
825,2016-12-18,Portugal,Kashima,FIFA Club World Cup,5,2,0.4000,3
883,2017-12-13,Portugal,Al-Jazira,FIFA Club World Cup,6,5,0.8333,1
884,2017-12-16,Portugal,Gremio,FIFA Club World Cup,7,6,0.8571,1
1128,2022-09-08,Portugal,Real Sociedad,UEFA Europa League,2,0,0.0000,0
1129,2022-09-15,Portugal,Sheriff Tiraspol,UEFA Europa League,3,0,0.0000,1
1132,2022-10-06,Portugal,Omonia Nicosia,UEFA Europa League,4,1,0.2500,0
1134,2022-10-13,Portugal,Omonia Nicosia,UEFA Europa League,5,1,0.2000,0
1136,2022-10-27,Portugal,Sheriff Tiraspol,UEFA Europa League,6,1,0.1667,1
1138,2022-11-03,Portugal,Real Sociedad,UEFA Europa League,7,2,0.2857,0

In [51]:
# Inspect opponent H2H features on the corrupted rows

h2h_impact = df.loc[
    list(team_corrections.keys()),
    [
        "date",
        "team",
        "opponent",
        "opponent_prior_meetings_pre",
        "ronaldo_goals_vs_opponent_pre",
        "ronaldo_goals_per_game_vs_opponent_pre",
        "team_h2h_wins_pre",
        "team_h2h_draws_pre",
        "team_h2h_losses_pre",
    ]
].copy()

display(h2h_impact)

,date,team,opponent,opponent_prior_meetings_pre,ronaldo_goals_vs_opponent_pre,ronaldo_goals_per_game_vs_opponent_pre,team_h2h_wins_pre,team_h2h_draws_pre,team_h2h_losses_pre
1,2002-09-19,Portugal,Partizan Belgrade,0,0,NaN,0,0,0
3,2002-10-03,Portugal,Partizan Belgrade,1,0,0.0000,0,0,1
350,2008-12-18,Portugal,Gamba Osaka,0,0,NaN,0,0,0
351,2008-12-21,Portugal,Liga de Quito,0,0,NaN,0,0,0
710,2014-12-16,Portugal,Cruz Azul,0,0,NaN,0,0,0
711,2014-12-20,Portugal,San Lorenzo,0,0,NaN,0,0,0
824,2016-12-15,Portugal,Club America,0,0,NaN,0,0,0
825,2016-12-18,Portugal,Kashima,0,0,NaN,0,0,0
883,2017-12-13,Portugal,Al-Jazira,0,0,NaN,0,0,0
884,2017-12-16,Portugal,Gremio,0,0,NaN,0,0,0
1128,2022-09-08,Portugal,Real Sociedad,9,15,1.6667,9,0,0
1129,2022-09-15,Portugal,Sheriff Tiraspol,0,0,NaN,0,0,0
1132,2022-10-06,Portugal,Omonia Nicosia,0,0,NaN,0,0,0
1134,2022-10-13,Portugal,Omonia Nicosia,1,0,0.0000,1,0,0
1136,2022-10-27,Portugal,Sheriff Tiraspol,1,1,1.0000,1,0,0
1138,2022-11-03,Portugal,Real Sociedad,10,15,1.5000,9,0,1

In [53]:
# Inspect recent team-form features on corrupted matches

team_form_impact = df.loc[
    list(team_corrections.keys()),
    [
        "date",
        "team",
        "opponent",
        "team_points_last_5_ronaldo_apps_pre",
        "team_points_last_10_ronaldo_apps_pre",
        "team_win_rate_last_5_ronaldo_apps_pre",
        "team_unbeaten_rate_last_5_ronaldo_apps_pre",
        "team_goals_for_last_5_scored_matches_pre",
        "team_goals_against_last_5_scored_matches_pre",
        "team_score_coverage_last_5_pre",
    ]
].copy()

display(team_form_impact)

,date,team,opponent,team_points_last_5_ronaldo_apps_pre,team_points_last_10_ronaldo_apps_pre,team_win_rate_last_5_ronaldo_apps_pre,team_unbeaten_rate_last_5_ronaldo_apps_pre,team_goals_for_last_5_scored_matches_pre,team_goals_against_last_5_scored_matches_pre,team_score_coverage_last_5_pre
1,2002-09-19,Portugal,Partizan Belgrade,0,0,NaN,NaN,NaN,NaN,0
3,2002-10-03,Portugal,Partizan Belgrade,0,0,0.0,0.0,NaN,NaN,0
350,2008-12-18,Portugal,Gamba Osaka,5,15,0.2,0.6,5.0,4.0,2
351,2008-12-21,Portugal,Liga de Quito,5,15,0.2,0.6,2.0,3.0,1
710,2014-12-16,Portugal,Cruz Azul,12,22,0.8,0.8,2.0,2.0,2
711,2014-12-20,Portugal,San Lorenzo,12,22,0.8,0.8,4.0,1.0,2
824,2016-12-15,Portugal,Club America,15,24,1.0,1.0,19.0,1.0,5
825,2016-12-18,Portugal,Kashima,15,26,1.0,1.0,19.0,1.0,5
883,2017-12-13,Portugal,Al-Jazira,12,22,0.8,0.8,10.0,1.0,5
884,2017-12-16,Portugal,Gremio,15,25,1.0,1.0,12.0,2.0,5
1128,2022-09-08,Portugal,Real Sociedad,13,23,0.8,1.0,12.0,2.0,5
1129,2022-09-15,Portugal,Sheriff Tiraspol,10,20,0.6,0.8,9.0,2.0,5
1132,2022-10-06,Portugal,Omonia Nicosia,9,19,0.6,0.6,8.0,2.0,5
1134,2022-10-13,Portugal,Omonia Nicosia,9,22,0.6,0.6,9.0,4.0,5
1136,2022-10-27,Portugal,Sheriff Tiraspol,12,22,0.8,0.8,10.0,3.0,5
1138,2022-11-03,Portugal,Real Sociedad,12,22,0.8,0.8,11.0,3.0,5

In [55]:
# Inspect Manchester United matches before the Gamba Osaka game

man_utd_before_gamba = df[
    (df["team"] == "Manchester United")
    & (df["date"] < pd.Timestamp("2008-12-18"))
].tail(10)[
    [
        "date",
        "opponent",
        "competition",
        "target_goals"
    ]
]

display(man_utd_before_gamba)

print("\nStored form on the Gamba Osaka row:")
display(
    df.loc[[350], [
        "team_points_last_5_ronaldo_apps_pre",
        "team_points_last_10_ronaldo_apps_pre",
        "team_win_rate_last_5_ronaldo_apps_pre",
        "team_unbeaten_rate_last_5_ronaldo_apps_pre",
        "team_goals_for_last_5_scored_matches_pre",
        "team_goals_against_last_5_scored_matches_pre",
        "team_score_coverage_last_5_pre",
    ]]
)

          date           opponent            competition  target_goals
339 2008-10-29    West Ham United         Premier League             2
340 2008-11-01          Hull City         Premier League             2
341 2008-11-05             Celtic  UEFA Champions League             0
342 2008-11-08            Arsenal         Premier League             0
343 2008-11-15         Stoke City         Premier League             2
345 2008-11-22        Aston Villa         Premier League             0
346 2008-11-25         Villarreal  UEFA Champions League             0
347 2008-11-30    Manchester City         Premier League             0
348 2008-12-06         Sunderland         Premier League             0
349 2008-12-13  Tottenham Hotspur         Premier League             0

Stored form on the Gamba Osaka row:

,team_points_last_5_ronaldo_apps_pre,team_points_last_10_ronaldo_apps_pre,team_win_rate_last_5_ronaldo_apps_pre,team_unbeaten_rate_last_5_ronaldo_apps_pre,team_goals_for_last_5_scored_matches_pre,team_goals_against_last_5_scored_matches_pre,team_score_coverage_last_5_pre
350,5,15,0.2,0.6,5.0,4.0,2

In [57]:
# Inspect matchup Elo around corrupted matches

elo_check = df.loc[
    [
        349, 350, 351, 352,
        709, 710, 711, 712,
        1127, 1128, 1129, 1130
    ],
    [
        "date",
        "team",
        "opponent",
        "team_matchup_elo_pre",
        "opponent_matchup_elo_pre",
        "matchup_elo_diff_pre",
        "opponent_matchup_elo_games_pre",
    ]
].copy()

display(elo_check)

,date,team,opponent,team_matchup_elo_pre,opponent_matchup_elo_pre,matchup_elo_diff_pre,opponent_matchup_elo_games_pre
349,2008-12-13,Manchester United,Tottenham Hotspur,1720.13,1470.58,249.55,10
350,2008-12-18,Portugal,Gamba Osaka,1596.97,1500.00,96.97,0
351,2008-12-21,Portugal,Liga de Quito,1604.25,1500.00,104.25,0
352,2008-12-26,Manchester United,Stoke City,1713.97,1495.58,218.39,1
709,2014-12-12,Real Madrid,Almeria,1789.05,1483.73,305.32,5
710,2014-12-16,Portugal,Cruz Azul,1642.73,1500.00,142.73,0
711,2014-12-20,Portugal,San Lorenzo,1648.84,1500.00,148.84,0
712,2015-01-04,Real Madrid,Valencia,1791.99,1495.35,296.64,11
1127,2022-09-04,Manchester United,Arsenal,1605.91,1536.92,68.99,17
1128,2022-09-08,Portugal,Real Sociedad,1675.22,1463.32,211.90,9
1129,2022-09-15,Portugal,Sheriff Tiraspol,1659.78,1500.00,159.78,0
1130,2022-09-24,Portugal,Czech Republic,1665.48,1481.99,183.49,3

In [59]:
# List every team/competition combination for final domain review

team_comp_check = (
    df.groupby(["team", "competition", "competition_type"])
      .size()
      .reset_index(name="appearances")
      .sort_values(["team", "competition"])
)

with pd.option_context("display.max_rows", None):
    display(team_comp_check)

,team,competition,competition_type,appearances
0,Al-Nassr,AFC Champions League,continental_club,9
1,Al-Nassr,AFC Champions League Elite,continental_club,8
2,Al-Nassr,AFC Champions League Two,continental_club,4
3,Al-Nassr,Arab Club Champions Cup,domestic_or_other_cup,6
4,Al-Nassr,King's Cup,domestic_or_other_cup,8
5,Al-Nassr,Pro League,domestic_league,110
6,Al-Nassr,Saudi Super Cup,domestic_or_other_cup,6
7,Juventus,Coppa Italia,domestic_or_other_cup,10
8,Juventus,Serie A,domestic_league,98
9,Juventus,Supercoppa Italiana,domestic_or_other_cup,3
10,Juventus,UEFA Champions League,continental_club,23
11,Manchester United,Champions League Qualifying,continental_club,3
12,Manchester United,FA Community Shield,domestic_or_other_cup,1
13,Manchester United,FA Cup,domestic_or_other_cup,27
14,Manchester United,League Cup,domestic_or_other_cup,12
15,Manchester United,Premier League,domestic_league,236
16,Manchester United,UEFA Champions League,continental_club,59
17,Portugal,Confederations Cup,international,4
18,Portugal,Euro Championship,international,30
19,Portugal,Euros Qualifier,international,44
20,Portugal,FIFA Club World Cup,international,8
21,Portugal,International Friendly,international,56
22,Portugal,UEFA Europa League,international,8
23,Portugal,UEFA Nations League,international,20
24,Portugal,World Cup,international,27
25,Portugal,World Cup - Qualification Europe,international,52
26,Real Madrid,Copa del Rey,domestic_or_other_cup,30
27,Real Madrid,La Liga,domestic_league,292
28,Real Madrid,Supercopa de Espana,domestic_or_other_cup,7
29,Real Madrid,UEFA Champions League,continental_club,101
30,Real Madrid,UEFA Super Cup,domestic_or_other_cup,2
31,Sporting CP,Champions League Qualifying,continental_club,1
32,Sporting CP,Primeira Liga,domestic_league,25
33,Sporting CP,Taça de Portugal,domestic_or_other_cup,3

In [61]:
# Step 1A — Find opponent names that may represent the same team

opponent_names = sorted(df["opponent"].dropna().unique())

for name in opponent_names:
    print(name)

AC Milan
AS Roma
Aalborg
Abha
Académica
Ajax
Al Ahli Doha
Al Ain
Al Baten
Al Khaleej Saihat
Al Kholood
Al Najma
Al Okhdood
Al Orubah
Al Riyadh
Al Shabab
Al Shorta
Al Taawon
Al Taee
Al Wehda Club
Al Zawra'a
Al-Adalah
Al-Ahli Jeddah
Al-Duhail SC
Al-Ettifaq
Al-Fateh
Al-Fayha
Al-Gharafa
Al-Hazm
Al-Hilal
Al-Ittihad FC
Al-Jazira
Al-Qadisiyah FC
Al-Raed
Al-Rayyan SC
Al-Wasl FC
Alaves
Albania
Algeria
Almeria
Andorra
Angola
Apoel Nicosia
Argentina
Armenia
Arsenal
Aston Villa
Atalanta
Athletic Club
Atletico Madrid
Austria
Auxerre
Azerbaijan
BSC Young Boys
Barcelona
Bayer Leverkusen
Bayern Munich
Beira-Mar
Belenenses
Belgium
Benevento
Benfica
Birmingham City
Blackburn Rovers
Boavista
Bologna
Bolton Wanderers
Borussia Dortmund
Bosnia & Herzegovina
Bosnia and Herzegovina
Brazil
Brentford
Brighton
Bulgaria
Burnley
Burton Albion
CSKA Moscow
Cagliari
Cameroon
Canada
Cape Verde
Celta Vigo
Celtic
Charlton Athletic
Chelsea
Chievo
Chile
China
Club America
Colombia
Congo DR
Cordoba
Croatia
Crotone
Cruz Azul
Crystal Palace
Cyprus
Czech Republic
Damac
Debrecen
Denmark
Deportivo La Coruna
Derby County
Dhamk
Dinamo Bucharest
Dinamo Zagreb
Dynamo Kyiv
Ecuador
Egypt
Eibar
Elche
Empoli
England
Espanyol
Estarreja
Esteghlal FC
Estonia
Everton
Exeter City
FC Basel 1893
FC Copenhagen
FC Oliveira do Hospital
FC Porto
FC Schalke 04
FC Zurich
FYR Macedonia
Faroe Islands
Fenerbahce
Ferencvarosi TC
Finland
Fiorentina
France
Frosinone
Fulham
Galatasaray
Gamba Osaka
Genoa
Georgia
Germany
Getafe
Ghana
Gil Vicente
Girona
Glasgow Rangers
Granada CF
Greece
Gremio
Hull City
Hungary
Hércules
Iceland
Inter Milan
Iran
Israel
Istiqlol
Italy
Ivory Coast
Juventus
Kashima
Kawasaki Frontale
Kazakhstan
Las Palmas
Latvia
Lazio
Lecce
Leeds
Leeds United
Leganes
Legia Warszawa
Leicester
Leicester City
Leiria
Levante
Liechtenstein
Liga de Quito
Lille
Lithuania
Liverpool
Lokomotiv Moscow
Ludogorets
Luxembourg
Lyon
Malaga
Mallorca
Malmo FF
Manchester City
Manchester United
Maritimo de Funchal
Marseille
Mexico
Middlesbrough
Millwall
Moreirense
Morocco
Mozambique
NEOM
Nacional da Madeira
Napoli
Naval
Netherlands
New Zealand
Newcastle
Newcastle United
Nigeria
North Korea
North Macedonia
Northampton Town
Northern Ireland
Norway
Norwich
Norwich City
Omonia Nicosia
Osasuna
Panama
Panathinaikos
Paris Saint Germain
Parma
Partizan Belgrade
Persepolis FC
Poland
Portsmouth
Qatar
Racing Santander
Raja Casablanca
Rayo Vallecano
Reading
Real Betis
Real Murcia
Real Sociedad
Real Valladolid
Real Zaragoza
Rep. Of Ireland
Republic of Ireland
Roma
Russia
SD Ponferradina
Sampdoria
San Lorenzo
Santa Clara
Sassuolo
Saudi Arabia
Scotland
Serbia
Sevilla
Shabab Al Ahli Dubai
Shakhtar Donetsk
Sheffield United
Sheriff Tiraspol
Slovakia
Slovenia
South Africa
South Korea
Southampton
Southend United
Spain
Spal
Sparta Prague
Spezia
Sporting Braga
Sporting CP
Sporting Gijon
Stoke City
Sunderland
Sweden
Switzerland
Tenerife
Torino
Tottenham
Tottenham Hotspur
Turkey
Türkiye
US Monastirienne
USA
Udinese
Ukraine
Uruguay
Uzbekistan
Valencia
Valladolid
Verona
VfB Stuttgart
VfL Wolfsburg
Villarreal
Vitoria Guimaraes
Vitoria Setubal
Wales
Watford
West Bromwich Albion
West Ham
West Ham United
Wigan Athletic
Wolverhampton Wanderers
Wolves
Xerez
Yokohama F. Marinos
Zamalek SC
Zaragoza
andorra

In [63]:
# Inspect suspected opponent-name aliases

alias_candidates = [
    "Bosnia & Herzegovina",
    "Bosnia and Herzegovina",
    "Rep. Of Ireland",
    "Republic of Ireland",
    "Turkey",
    "Türkiye",
    "Andorra",
    "andorra",
    "Leeds",
    "Leeds United",
    "Leicester",
    "Leicester City",
    "Newcastle",
    "Newcastle United",
    "Norwich",
    "Norwich City",
    "Tottenham",
    "Tottenham Hotspur",
    "West Ham",
    "West Ham United",
    "Wolves",
    "Wolverhampton Wanderers",
    "Roma",
    "AS Roma",
    "Valladolid",
    "Real Valladolid",
    "Zaragoza",
    "Real Zaragoza",
]

alias_check = (
    df[df["opponent"].isin(alias_candidates)]
    .groupby(["opponent", "team", "competition"])
    .agg(
        appearances=("match_id", "count"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
    .reset_index()
    .sort_values(["opponent", "first_date"])
)

display(alias_check)

,opponent,team,competition,appearances,first_date,last_date
2,AS Roma,Real Madrid,UEFA Champions League,2,2016-02-17,2016-03-08
1,AS Roma,Juventus,Serie A,5,2018-12-22,2021-02-06
0,AS Roma,Juventus,Coppa Italia,1,2020-01-22,2020-01-22
3,Andorra,Portugal,International Friendly,1,2020-11-11,2020-11-11
4,Bosnia & Herzegovina,Portugal,Euros Qualifier,2,2023-06-17,2023-10-16
5,Bosnia and Herzegovina,Portugal,Euros Qualifier,2,2011-11-11,2011-11-15
6,Leeds,Manchester United,Premier League,1,2022-02-20,2022-02-20
7,Leeds United,Manchester United,Premier League,1,2003-10-18,2003-10-18
8,Leicester,Manchester United,Premier League,2,2021-10-16,2022-09-01
9,Leicester City,Manchester United,Premier League,1,2004-04-13,2004-04-13
10,Newcastle,Manchester United,Premier League,3,2021-09-11,2022-10-16
12,Newcastle United,Manchester United,Premier League,10,2003-08-23,2009-03-04
11,Newcastle United,Manchester United,FA Cup,1,2005-04-17,2005-04-17
13,Norwich,Manchester United,Premier League,2,2021-12-11,2022-04-16
14,Norwich City,Manchester United,Premier League,2,2004-08-21,2005-04-09
15,Real Valladolid,Real Madrid,La Liga,1,2010-03-14,2010-03-14
16,Real Zaragoza,Real Madrid,La Liga,2,2009-12-19,2010-04-24
18,Rep. Of Ireland,Portugal,World Cup - Qualification Europe,4,2021-09-01,2025-11-13
17,Rep. Of Ireland,Portugal,International Friendly,1,2024-06-11,2024-06-11
19,Republic of Ireland,Portugal,International Friendly,2,2005-02-09,2014-06-11
20,Roma,Manchester United,UEFA Champions League,4,2007-04-04,2008-04-01
22,Tottenham,Real Madrid,UEFA Champions League,2,2017-10-17,2017-11-01
21,Tottenham,Manchester United,Premier League,2,2021-10-30,2022-03-12
25,Tottenham Hotspur,Manchester United,Premier League,11,2003-12-21,2009-04-25
23,Tottenham Hotspur,Manchester United,FA Cup,2,2008-01-27,2009-01-24
24,Tottenham Hotspur,Manchester United,League Cup,1,2009-03-01,2009-03-01
26,Tottenham Hotspur,Real Madrid,UEFA Champions League,2,2011-04-05,2011-04-13
27,Turkey,Portugal,International Friendly,1,2012-06-02,2012-06-02
28,Türkiye,Portugal,Euro Championship,2,2008-06-07,2024-06-22
29,Türkiye,Portugal,World Cup - Qualification Europe,1,2022-03-24,2022-03-24
30,Valladolid,Real Madrid,La Liga,3,2012-12-08,2014-05-07
31,West Ham,Manchester United,Premier League,3,2021-09-19,2022-10-30
32,West Ham United,Manchester United,Premier League,7,2006-03-29,2009-02-08
33,Wolverhampton Wanderers,Manchester United,Premier League,2,2003-08-27,2004-01-17
34,Wolves,Manchester United,Premier League,1,2022-01-03,2022-01-03
35,Zaragoza,Real Madrid,La Liga,5,2010-12-12,2013-03-30
36,andorra,Portugal,World Cup - Qualification Europe,2,2016-10-07,2017-10-07

In [65]:
# Check whether opponent aliases split H2H history

alias_h2h_check = df[
    df["opponent"].isin([
        "AS Roma",
        "Bosnia & Herzegovina",
        "Leeds",
        "Leicester",
        "Newcastle",
        "Norwich",
        "Rep. Of Ireland",
        "Tottenham",
        "Turkey",
        "Valladolid",
        "West Ham",
        "Wolves",
        "Zaragoza",
        "Andorra",
    ])
][
    [
        "date",
        "team",
        "opponent",
        "opponent_prior_meetings_pre",
        "ronaldo_goals_vs_opponent_pre",
        "ronaldo_goals_per_game_vs_opponent_pre",
    ]
].sort_values("date")

display(alias_h2h_check)

,date,team,opponent,opponent_prior_meetings_pre,ronaldo_goals_vs_opponent_pre,ronaldo_goals_per_game_vs_opponent_pre
459,2010-12-12,Real Madrid,Zaragoza,0,0,NaN
496,2011-08-28,Real Madrid,Zaragoza,1,1,1.0000
529,2012-01-28,Real Madrid,Zaragoza,2,4,2.0000
556,2012-06-02,Portugal,Turkey,0,0,NaN
581,2012-11-03,Real Madrid,Zaragoza,3,5,1.6667
589,2012-12-08,Real Madrid,Valladolid,0,0,NaN
612,2013-03-30,Real Madrid,Zaragoza,4,5,1.2500
620,2013-05-04,Real Madrid,Valladolid,1,0,0.0000
677,2014-05-07,Real Madrid,Valladolid,2,2,1.0000
776,2016-02-17,Real Madrid,AS Roma,0,0,NaN
781,2016-03-08,Real Madrid,AS Roma,1,1,1.0000
872,2017-10-17,Real Madrid,Tottenham,0,0,NaN
875,2017-11-01,Real Madrid,Tottenham,1,1,1.0000
936,2018-12-22,Juventus,AS Roma,2,2,1.0000
958,2019-05-12,Juventus,AS Roma,3,2,0.6667
990,2020-01-12,Juventus,AS Roma,4,2,0.5000
992,2020-01-22,Juventus,AS Roma,5,3,0.6000
1016,2020-09-27,Juventus,AS Roma,6,4,0.6667
1022,2020-11-11,Portugal,Andorra,0,0,NaN
1043,2021-02-06,Juventus,AS Roma,7,6,0.8571
1074,2021-09-01,Portugal,Rep. Of Ireland,0,0,NaN
1075,2021-09-11,Manchester United,Newcastle,0,0,NaN
1077,2021-09-19,Manchester United,West Ham,0,0,NaN
1083,2021-10-16,Manchester United,Leicester,0,0,NaN
1086,2021-10-30,Manchester United,Tottenham,2,2,1.0000
1089,2021-11-11,Portugal,Rep. Of Ireland,1,2,2.0000
1096,2021-12-11,Manchester United,Norwich,0,0,NaN
1097,2021-12-27,Manchester United,Newcastle,1,2,2.0000
1099,2022-01-03,Manchester United,Wolves,0,0,NaN
1101,2022-01-22,Manchester United,West Ham,1,1,1.0000
1106,2022-02-20,Manchester United,Leeds,0,0,NaN
1109,2022-03-12,Manchester United,Tottenham,3,3,1.0000
1114,2022-04-16,Manchester United,Norwich,1,1,1.0000
1126,2022-09-01,Manchester United,Leicester,1,0,0.0000
1135,2022-10-16,Manchester United,Newcastle,2,2,1.0000
1137,2022-10-30,Manchester United,West Ham,2,1,0.5000
1166,2023-06-17,Portugal,Bosnia & Herzegovina,0,0,NaN
1187,2023-10-16,Portugal,Bosnia & Herzegovina,1,0,0.0000
1225,2024-06-11,Portugal,Rep. Of Ireland,2,2,1.0000
1289,2025-10-11,Portugal,Rep. Of Ireland,3,4,1.3333
1296,2025-11-13,Portugal,Rep. Of Ireland,4,4,1.0000

In [67]:
# Check whether opponent aliases also reset Elo history

elo_alias_check = df[
    df["opponent"].isin([
        "Bosnia & Herzegovina",
        "Rep. Of Ireland",
        "Leeds",
        "Leicester",
        "Newcastle",
        "Norwich",
        "Tottenham",
        "West Ham",
        "Wolves",
        "AS Roma",
        "Valladolid",
        "Zaragoza",
        "Andorra",
    ])
][
    [
        "date",
        "team",
        "opponent",
        "opponent_matchup_elo_pre",
        "opponent_matchup_elo_games_pre",
    ]
].sort_values("date")

display(elo_alias_check)

,date,team,opponent,opponent_matchup_elo_pre,opponent_matchup_elo_games_pre
459,2010-12-12,Real Madrid,Zaragoza,1500.00,0
496,2011-08-28,Real Madrid,Zaragoza,1495.37,1
529,2012-01-28,Real Madrid,Zaragoza,1491.28,2
581,2012-11-03,Real Madrid,Zaragoza,1487.80,3
589,2012-12-08,Real Madrid,Valladolid,1500.00,0
612,2013-03-30,Real Madrid,Zaragoza,1484.09,4
620,2013-05-04,Real Madrid,Valladolid,1495.91,1
677,2014-05-07,Real Madrid,Valladolid,1491.79,2
776,2016-02-17,Real Madrid,AS Roma,1500.00,0
781,2016-03-08,Real Madrid,AS Roma,1495.83,1
872,2017-10-17,Real Madrid,Tottenham,1500.00,0
875,2017-11-01,Real Madrid,Tottenham,1506.43,1
936,2018-12-22,Juventus,AS Roma,1491.58,2
958,2019-05-12,Juventus,AS Roma,1485.73,3
990,2020-01-12,Juventus,AS Roma,1500.17,4
992,2020-01-22,Juventus,AS Roma,1495.08,5
1016,2020-09-27,Juventus,AS Roma,1490.31,6
1022,2020-11-11,Portugal,Andorra,1500.00,0
1043,2021-02-06,Juventus,AS Roma,1494.49,7
1074,2021-09-01,Portugal,Rep. Of Ireland,1500.00,0
1075,2021-09-11,Manchester United,Newcastle,1500.00,0
1077,2021-09-19,Manchester United,West Ham,1500.00,0
1083,2021-10-16,Manchester United,Leicester,1500.00,0
1086,2021-10-30,Manchester United,Tottenham,1522.40,2
1089,2021-11-11,Portugal,Rep. Of Ireland,1494.33,1
1096,2021-12-11,Manchester United,Norwich,1500.00,0
1097,2021-12-27,Manchester United,Newcastle,1495.37,1
1099,2022-01-03,Manchester United,Wolves,1500.00,0
1101,2022-01-22,Manchester United,West Ham,1495.15,1
1106,2022-02-20,Manchester United,Leeds,1500.00,0
1109,2022-03-12,Manchester United,Tottenham,1516.25,3
1114,2022-04-16,Manchester United,Norwich,1494.16,1
1126,2022-09-01,Manchester United,Leicester,1514.91,1
1135,2022-10-16,Manchester United,Newcastle,1499.78,2
1137,2022-10-30,Manchester United,West Ham,1489.40,2
1166,2023-06-17,Portugal,Bosnia & Herzegovina,1500.00,0
1187,2023-10-16,Portugal,Bosnia & Herzegovina,1494.63,1
1225,2024-06-11,Portugal,Rep. Of Ireland,1499.15,2
1289,2025-10-11,Portugal,Rep. Of Ireland,1494.20,3
1296,2025-11-13,Portugal,Rep. Of Ireland,1489.71,4

In [69]:
# Find other likely duplicate opponent names

from difflib import SequenceMatcher

opponents = sorted(df["opponent"].dropna().unique())
similar_pairs = []

for i, name_a in enumerate(opponents):
    for name_b in opponents[i + 1:]:
        score = SequenceMatcher(None, name_a.lower(), name_b.lower()).ratio()

        if score >= 0.72:
            similar_pairs.append((name_a, name_b, round(score, 3)))

similar_pairs = (
    pd.DataFrame(
        similar_pairs,
        columns=["opponent_a", "opponent_b", "similarity"]
    )
    .sort_values("similarity", ascending=False)
    .reset_index(drop=True)
)

display(similar_pairs)

              opponent_a               opponent_b  similarity
0                Andorra                  andorra       1.000
1   Bosnia & Herzegovina   Bosnia and Herzegovina       0.905
2                Algeria                  Almeria       0.857
3        Rep. Of Ireland      Republic of Ireland       0.824
4            North Korea              South Korea       0.818
5        Manchester City        Manchester United       0.812
6        Real Valladolid               Valladolid       0.800
7             Al Kholood               Al Okhdood       0.800
8            Exeter City           Leicester City       0.800
9          FYR Macedonia          North Macedonia       0.786
10             Leicester           Leicester City       0.783
11      Bolton Wanderers  Wolverhampton Wanderers       0.769
12               Everton                   Verona       0.769
13               Almeria                   Leiria       0.769
14               Algeria                   Leiria       0.769
15         Real Zaragoza                 Zaragoza       0.762
16        Leicester City          Manchester City       0.759
17             Argentina                  Armenia       0.750
18              Slovakia                 Slovenia       0.750
19              Al-Fateh                 Al-Fayha       0.750
20             Argentina               Fiorentina       0.737
21               Norwich             Norwich City       0.737
22               AS Roma                     Roma       0.727
23                Panama                    Parma       0.727
24                Chievo                    Chile       0.727
25                Alaves                    Wales       0.727
26                 Wales                   Wolves       0.727
27             Newcastle         Newcastle United       0.720
28        Sporting Braga              Sporting CP       0.720
29           Sporting CP           Sporting Gijon       0.720

In [71]:
# Inspect Macedonia naming variants

macedonia_check = df[
    df["opponent"].isin(["FYR Macedonia", "North Macedonia"])
][
    [
        "date",
        "team",
        "opponent",
        "competition",
        "opponent_prior_meetings_pre",
        "ronaldo_goals_vs_opponent_pre",
        "opponent_matchup_elo_pre",
        "opponent_matchup_elo_games_pre",
    ]
].sort_values("date")

display(macedonia_check)

,date,team,opponent,competition,opponent_prior_meetings_pre,ronaldo_goals_vs_opponent_pre,opponent_matchup_elo_pre,opponent_matchup_elo_games_pre
555,2012-05-26,Portugal,North Macedonia,International Friendly,0,0,1500.0,0
1112,2022-03-29,Portugal,FYR Macedonia,World Cup - Qualification Europe,0,0,1500.0,0

In [73]:
# Define confirmed opponent aliases

opponent_alias_map = {
    "andorra": "Andorra",
    "Bosnia and Herzegovina": "Bosnia & Herzegovina",
    "Rep. Of Ireland": "Republic of Ireland",
    "Turkey": "Türkiye",
    "FYR Macedonia": "North Macedonia",

    "Leeds": "Leeds United",
    "Leicester": "Leicester City",
    "Newcastle": "Newcastle United",
    "Norwich": "Norwich City",
    "Tottenham": "Tottenham Hotspur",
    "West Ham": "West Ham United",
    "Wolves": "Wolverhampton Wanderers",

    "Roma": "AS Roma",
    "Valladolid": "Real Valladolid",
    "Zaragoza": "Real Zaragoza",
}

alias_impact = (
    df[df["opponent"].isin(opponent_alias_map)]
    ["opponent"]
    .value_counts()
    .rename_axis("original_name")
    .reset_index(name="rows_affected")
)

alias_impact["canonical_name"] = alias_impact["original_name"].map(opponent_alias_map)

display(alias_impact)

print("Total rows that would be renamed:", alias_impact["rows_affected"].sum())

             original_name  rows_affected           canonical_name
0                 Zaragoza              5            Real Zaragoza
1          Rep. Of Ireland              5      Republic of Ireland
2                     Roma              4                  AS Roma
3                Tottenham              4        Tottenham Hotspur
4               Valladolid              3          Real Valladolid
5                Newcastle              3         Newcastle United
6                 West Ham              3          West Ham United
7   Bosnia and Herzegovina              2     Bosnia & Herzegovina
8                  andorra              2                  Andorra
9                Leicester              2           Leicester City
10                 Norwich              2             Norwich City
11                  Turkey              1                  Türkiye
12                  Wolves              1  Wolverhampton Wanderers
13                   Leeds              1             Leeds United
14           FYR Macedonia              1          North Macedonia

Total rows that would be renamed: 39

In [75]:
# Inspect match_id construction

match_id_check = df[
    [
        "match_id",
        "date",
        "team",
        "opponent",
        "competition",
    ]
].copy()

display(match_id_check.head(10))

print("\n16 corrupted-team match IDs:")
display(
    match_id_check.loc[list(team_corrections.keys())]
)

,match_id,date,team,opponent,competition
0,2002-08-14_Sporting_CP_Inter_Milan_1,2002-08-14,Sporting CP,Inter Milan,Champions League Qualifying
1,2002-09-19_Portugal_Partizan_Belgrade_2,2002-09-19,Portugal,Partizan Belgrade,UEFA Europa League
2,2002-09-30_Sporting_CP_Sporting_Braga_3,2002-09-30,Sporting CP,Sporting Braga,Primeira Liga
3,2002-10-03_Portugal_Partizan_Belgrade_4,2002-10-03,Portugal,Partizan Belgrade,UEFA Europa League
4,2002-10-07_Sporting_CP_Moreirense_5,2002-10-07,Sporting CP,Moreirense,Primeira Liga
5,2002-10-20_Sporting_CP_Belenenses_6,2002-10-20,Sporting CP,Belenenses,Primeira Liga
6,2002-10-26_Sporting_CP_Boavista_7,2002-10-26,Sporting CP,Boavista,Primeira Liga
7,2002-11-02_Sporting_CP_Gil_Vicente_8,2002-11-02,Sporting CP,Gil Vicente,Primeira Liga
8,2002-11-08_Sporting_CP_Vitoria_Guimaraes_9,2002-11-08,Sporting CP,Vitoria Guimaraes,Primeira Liga
9,2002-11-15_Sporting_CP_Maritimo_de_Funchal_10,2002-11-15,Sporting CP,Maritimo de Funchal,Primeira Liga

16 corrupted-team match IDs:

,match_id,date,team,opponent,competition
1,2002-09-19_Portugal_Partizan_Belgrade_2,2002-09-19,Portugal,Partizan Belgrade,UEFA Europa League
3,2002-10-03_Portugal_Partizan_Belgrade_4,2002-10-03,Portugal,Partizan Belgrade,UEFA Europa League
350,2008-12-18_Portugal_Gamba_Osaka_351,2008-12-18,Portugal,Gamba Osaka,FIFA Club World Cup
351,2008-12-21_Portugal_Liga_de_Quito_352,2008-12-21,Portugal,Liga de Quito,FIFA Club World Cup
710,2014-12-16_Portugal_Cruz_Azul_711,2014-12-16,Portugal,Cruz Azul,FIFA Club World Cup
711,2014-12-20_Portugal_San_Lorenzo_712,2014-12-20,Portugal,San Lorenzo,FIFA Club World Cup
824,2016-12-15_Portugal_Club_America_825,2016-12-15,Portugal,Club America,FIFA Club World Cup
825,2016-12-18_Portugal_Kashima_826,2016-12-18,Portugal,Kashima,FIFA Club World Cup
883,2017-12-13_Portugal_Al-Jazira_884,2017-12-13,Portugal,Al-Jazira,FIFA Club World Cup
884,2017-12-16_Portugal_Gremio_885,2017-12-16,Portugal,Gremio,FIFA Club World Cup
1128,2022-09-08_Portugal_Real_Sociedad_1129,2022-09-08,Portugal,Real Sociedad,UEFA Europa League
1129,2022-09-15_Portugal_Sheriff_Tiraspol_1130,2022-09-15,Portugal,Sheriff Tiraspol,UEFA Europa League
1132,2022-10-06_Portugal_Omonia_Nicosia_1133,2022-10-06,Portugal,Omonia Nicosia,UEFA Europa League
1134,2022-10-13_Portugal_Omonia_Nicosia_1135,2022-10-13,Portugal,Omonia Nicosia,UEFA Europa League
1136,2022-10-27_Portugal_Sheriff_Tiraspol_1137,2022-10-27,Portugal,Sheriff Tiraspol,UEFA Europa League
1138,2022-11-03_Portugal_Real_Sociedad_1139,2022-11-03,Portugal,Real Sociedad,UEFA Europa League

In [77]:
# Build corrected identity fields without changing raw columns

df["team_corrected"] = df["team"]
df["opponent_corrected"] = df["opponent"]
df["competition_type_corrected"] = df["competition_type"]

# Correct the 16 known team assignments
for idx, corrected_team in team_corrections.items():
    df.loc[idx, "team_corrected"] = corrected_team

# Normalize confirmed opponent aliases
df["opponent_corrected"] = df["opponent"].replace(opponent_alias_map)

# Fix club competition classifications
df.loc[
    df["competition"].isin([
        "UEFA Europa League",
        "FIFA Club World Cup",
        "UEFA Super Cup",
    ]),
    "competition_type_corrected"
] = "continental_club"

# Rebuild match IDs using corrected identities
df["match_id_corrected"] = (
    df["date"].dt.strftime("%Y-%m-%d")
    + "_"
    + df["team_corrected"].str.replace(" ", "_", regex=False)
    + "_"
    + df["opponent_corrected"].str.replace(" ", "_", regex=False)
    + "_"
    + (df.index + 1).astype(str)
)

display(
    df.loc[list(team_corrections.keys()), [
        "match_id",
        "match_id_corrected",
        "team",
        "team_corrected",
        "competition",
        "competition_type",
        "competition_type_corrected",
    ]]
)

,match_id,match_id_corrected,team,team_corrected,competition,competition_type,competition_type_corrected
1,2002-09-19_Portugal_Partizan_Belgrade_2,2002-09-19_Sporting_CP_Partizan_Belgrade_2,Portugal,Sporting CP,UEFA Europa League,international,continental_club
3,2002-10-03_Portugal_Partizan_Belgrade_4,2002-10-03_Sporting_CP_Partizan_Belgrade_4,Portugal,Sporting CP,UEFA Europa League,international,continental_club
350,2008-12-18_Portugal_Gamba_Osaka_351,2008-12-18_Manchester_United_Gamba_Osaka_351,Portugal,Manchester United,FIFA Club World Cup,international,continental_club
351,2008-12-21_Portugal_Liga_de_Quito_352,2008-12-21_Manchester_United_Liga_de_Quito_352,Portugal,Manchester United,FIFA Club World Cup,international,continental_club
710,2014-12-16_Portugal_Cruz_Azul_711,2014-12-16_Real_Madrid_Cruz_Azul_711,Portugal,Real Madrid,FIFA Club World Cup,international,continental_club
711,2014-12-20_Portugal_San_Lorenzo_712,2014-12-20_Real_Madrid_San_Lorenzo_712,Portugal,Real Madrid,FIFA Club World Cup,international,continental_club
824,2016-12-15_Portugal_Club_America_825,2016-12-15_Real_Madrid_Club_America_825,Portugal,Real Madrid,FIFA Club World Cup,international,continental_club
825,2016-12-18_Portugal_Kashima_826,2016-12-18_Real_Madrid_Kashima_826,Portugal,Real Madrid,FIFA Club World Cup,international,continental_club
883,2017-12-13_Portugal_Al-Jazira_884,2017-12-13_Real_Madrid_Al-Jazira_884,Portugal,Real Madrid,FIFA Club World Cup,international,continental_club
884,2017-12-16_Portugal_Gremio_885,2017-12-16_Real_Madrid_Gremio_885,Portugal,Real Madrid,FIFA Club World Cup,international,continental_club
1128,2022-09-08_Portugal_Real_Sociedad_1129,2022-09-08_Manchester_United_Real_Sociedad_1129,Portugal,Manchester United,UEFA Europa League,international,continental_club
1129,2022-09-15_Portugal_Sheriff_Tiraspol_1130,2022-09-15_Manchester_United_Sheriff_Tiraspol_...,Portugal,Manchester United,UEFA Europa League,international,continental_club
1132,2022-10-06_Portugal_Omonia_Nicosia_1133,2022-10-06_Manchester_United_Omonia_Nicosia_1133,Portugal,Manchester United,UEFA Europa League,international,continental_club
1134,2022-10-13_Portugal_Omonia_Nicosia_1135,2022-10-13_Manchester_United_Omonia_Nicosia_1135,Portugal,Manchester United,UEFA Europa League,international,continental_club
1136,2022-10-27_Portugal_Sheriff_Tiraspol_1137,2022-10-27_Manchester_United_Sheriff_Tiraspol_...,Portugal,Manchester United,UEFA Europa League,international,continental_club
1138,2022-11-03_Portugal_Real_Sociedad_1139,2022-11-03_Manchester_United_Real_Sociedad_1139,Portugal,Manchester United,UEFA Europa League,international,continental_club

In [79]:
# Validate corrected identity fields

print("Corrected teams:")
print(df["team_corrected"].value_counts())

print("\nCorrected competition types:")
print(df["competition_type_corrected"].value_counts())

print("\nDuplicate corrected match IDs:",
      df["match_id_corrected"].duplicated().sum())

print("\nRows still showing Portugal in club competitions:")
display(
    df[
        (df["team_corrected"] == "Portugal")
        & (df["competition_type_corrected"] != "international")
    ][
        [
            "date",
            "team_corrected",
            "opponent_corrected",
            "competition",
            "competition_type_corrected",
        ]
    ]
)

print("\nCorrected Portugal appearances:",
      (df["team_corrected"] == "Portugal").sum())

Corrected teams:
team_corrected
Real Madrid          438
Manchester United    346
Portugal             233
Al-Nassr             151
Juventus             134
Sporting CP           31
Name: count, dtype: int64

Corrected competition types:
competition_type_corrected
domestic_league          761
international            233
continental_club         226
domestic_or_other_cup    113
Name: count, dtype: int64

Duplicate corrected match IDs: 0

Rows still showing Portugal in club competitions:

Empty DataFrame
Columns: [date, team_corrected, opponent_corrected, competition, competition_type_corrected]
Index: []

Corrected Portugal appearances: 233

In [81]:
# Step 1AK — Commit validated identity corrections

df["team"] = df["team_corrected"]
df["opponent"] = df["opponent_corrected"]
df["competition_type"] = df["competition_type_corrected"]
df["match_id"] = df["match_id_corrected"]

df.drop(
    columns=[
        "team_corrected",
        "opponent_corrected",
        "competition_type_corrected",
        "match_id_corrected",
    ],
    inplace=True,
)

print("Shape after identity corrections:", df.shape)
print("Duplicate match IDs:", df["match_id"].duplicated().sum())
print("Portugal appearances:", (df["team"] == "Portugal").sum())
print("Unique opponents:", df["opponent"].nunique())
print("Columns remaining:", len(df.columns))

Shape after identity corrections: (1333, 86)
Duplicate match IDs: 0
Portugal appearances: 233
Unique opponents: 283
Columns remaining: 86

In [83]:
# Define the stateful features affected by identity corrections

rebuild_candidates = [
    # Team history
    "team_appearances_with_ronaldo_pre",
    "team_goals_by_ronaldo_pre",
    "team_ronaldo_goals_per_game_pre",

    # Team recent form
    "team_points_last_5_ronaldo_apps_pre",
    "team_points_last_10_ronaldo_apps_pre",
    "team_win_rate_last_5_ronaldo_apps_pre",
    "team_unbeaten_rate_last_5_ronaldo_apps_pre",
    "team_goals_for_last_5_scored_matches_pre",
    "team_goals_against_last_5_scored_matches_pre",
    "team_score_coverage_last_5_pre",

    # Ronaldo vs opponent
    "opponent_prior_meetings_pre",
    "ronaldo_goals_vs_opponent_pre",
    "ronaldo_assists_vs_opponent_pre",
    "ronaldo_goals_per_game_vs_opponent_pre",
    "ronaldo_scoring_rate_vs_opponent_pre",
    "ronaldo_goals_last_3_vs_opponent_pre",

    # Team vs opponent H2H
    "team_h2h_wins_pre",
    "team_h2h_draws_pre",
    "team_h2h_losses_pre",
    "opponent_h2h_points_per_game_pre",
    "opponent_h2h_unbeaten_rate_pre",
    "opponent_goals_for_per_h2h_scored_match_pre",
    "opponent_goals_against_per_h2h_scored_match_pre",
    "opponent_clean_sheet_rate_h2h_scored_match_pre",
    "opponent_score_data_h2h_matches_pre",

    # Matchup Elo
    "team_matchup_elo_pre",
    "opponent_matchup_elo_pre",
    "matchup_elo_diff_pre",
    "opponent_matchup_elo_games_pre",
]

print("Features marked for reconstruction:", len(rebuild_candidates))

missing_columns = [
    col for col in rebuild_candidates
    if col not in df.columns
]

print("Missing from dataset:", missing_columns)

display(
    df[rebuild_candidates].dtypes.to_frame("dtype")
)

Features marked for reconstruction: 29
Missing from dataset: []

                                                   dtype
team_appearances_with_ronaldo_pre                  int64
team_goals_by_ronaldo_pre                          int64
team_ronaldo_goals_per_game_pre                  float64
team_points_last_5_ronaldo_apps_pre                int64
team_points_last_10_ronaldo_apps_pre               int64
team_win_rate_last_5_ronaldo_apps_pre            float64
team_unbeaten_rate_last_5_ronaldo_apps_pre       float64
team_goals_for_last_5_scored_matches_pre         float64
team_goals_against_last_5_scored_matches_pre     float64
team_score_coverage_last_5_pre                     int64
opponent_prior_meetings_pre                        int64
ronaldo_goals_vs_opponent_pre                      int64
ronaldo_assists_vs_opponent_pre                    int64
ronaldo_goals_per_game_vs_opponent_pre           float64
ronaldo_scoring_rate_vs_opponent_pre             float64
ronaldo_goals_last_3_vs_opponent_pre               int64
team_h2h_wins_pre                                  int64
team_h2h_draws_pre                                 int64
team_h2h_losses_pre                                int64
opponent_h2h_points_per_game_pre                 float64
opponent_h2h_unbeaten_rate_pre                   float64
opponent_goals_for_per_h2h_scored_match_pre      float64
opponent_goals_against_per_h2h_scored_match_pre  float64
opponent_clean_sheet_rate_h2h_scored_match_pre   float64
opponent_score_data_h2h_matches_pre                int64
team_matchup_elo_pre                             float64
opponent_matchup_elo_pre                         float64
matchup_elo_diff_pre                             float64
opponent_matchup_elo_games_pre                     int64

In [85]:
# Check what raw match information is available for reconstruction

search_terms = [
    "score",
    "result",
    "goal",
    "assist",
    "win",
    "draw",
    "loss",
    "point",
    "elo",
]

for term in search_terms:
    matches = [
        col for col in df.columns
        if term in col.lower()
    ]

    print(f"\n{term.upper()}:")
    print(matches)

SCORE:
['team_goals_for_last_5_scored_matches_pre', 'team_goals_against_last_5_scored_matches_pre', 'team_score_coverage_last_5_pre', 'opponent_goals_for_per_h2h_scored_match_pre', 'opponent_goals_against_per_h2h_scored_match_pre', 'opponent_clean_sheet_rate_h2h_scored_match_pre', 'opponent_score_data_h2h_matches_pre', 'target_scored']

RESULT:
[]

GOAL:
['career_goals_pre', 'goals_to_1000_pre', 'career_goals_per_game_pre', 'goals_last_3', 'goals_last_5', 'goals_last_10', 'goals_last_20', 'goals_per_game_last_5', 'goals_per_game_last_10', 'goals_per_game_last_20', 'multi_goal_rate_last_10', 'goals_ewma_pre', 'goalless_streak_games_pre', 'days_since_last_goal', 'season_goals_pre', 'season_goals_per_game_pre', 'team_goals_by_ronaldo_pre', 'team_ronaldo_goals_per_game_pre', 'team_goals_for_last_5_scored_matches_pre', 'team_goals_against_last_5_scored_matches_pre', 'ronaldo_goals_vs_opponent_pre', 'ronaldo_goals_per_game_vs_opponent_pre', 'ronaldo_goals_last_3_vs_opponent_pre', 'opponent_goals_for_per_h2h_scored_match_pre', 'opponent_goals_against_per_h2h_scored_match_pre', 'competition_goals_pre', 'competition_goals_per_game_pre', 'venue_goals_pre', 'venue_goals_per_game_pre', 'target_multi_goal', 'target_goals']

ASSIST:
['career_assists_pre', 'assists_last_5', 'assists_last_10', 'assists_ewma_pre', 'season_assists_pre', 'ronaldo_assists_vs_opponent_pre']

WIN:
['team_win_rate_last_5_ronaldo_apps_pre', 'team_h2h_wins_pre']

DRAW:
['team_h2h_draws_pre']

LOSS:
['team_h2h_losses_pre']

POINT:
['team_points_last_5_ronaldo_apps_pre', 'team_points_last_10_ronaldo_apps_pre', 'opponent_h2h_points_per_game_pre']

ELO:
['team_matchup_elo_pre', 'opponent_matchup_elo_pre', 'matchup_elo_diff_pre', 'opponent_matchup_elo_games_pre']

In [87]:
# Inspect available project data files

from pathlib import Path

data_root = Path("../data")

if data_root.exists():
    files = sorted(
        path for path in data_root.rglob("*")
        if path.is_file()
    )

    print(f"Files found: {len(files)}\n")

    for path in files:
        print(path)
else:
    print("Could not find ../data from the current notebook location.")

Files found: 1

..\data\raw\ronaldo_complete_ml_dataset.csv

In [89]:
# the audited identity-corrected dataset


processed_dir = Path("../data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

output_path = processed_dir / "ronaldo_identity_corrected.csv"

df.to_csv(output_path, index=False)

print("Saved to:", output_path)
print("Shape:", df.shape)
print("Total goals:", df["target_goals"].sum())
print("Portugal appearances:", (df["team"] == "Portugal").sum())
print("Duplicate match IDs:", df["match_id"].duplicated().sum())

Saved to: ..\data\processed\ronaldo_identity_corrected.csv
Shape: (1333, 86)
Total goals: 978
Portugal appearances: 233
Duplicate match IDs: 0